### ISSUE TITLE
Stable-baselines3 compatibility

### ISSUE THREAD

**Issue by smarianimore** [LucaInis/Slime-Enviroment-GIT-#2]
Change custom Space in single agent environment to DiscreteSpace from Gymnasium to be compatible with Stable-baselines3

**Comment by vamsianumula** [comment]
I will start working on this. Is that fine?

**Comment by smarianimore** [comment]
Sure, let me know if you need assistance

What branch are going to start working with? `sm-baselines-api`?

**Comment by vamsianumula** [comment]
Yes, I am working on a new branch created from sm-baselines-api.

**Comment by smarianimore** [comment]
Nice

**Comment by vamsianumula** [comment]
Instead of converting to Discrete state space, I think MultiBinary([here](https://www.gymlibrary.dev/api/spaces/#multibinary)) space would be best one for our case right? But MultiBinary state space only supports A2C, PPO in stablebaselines3. Please give your suggestion on this.

**Comment by smarianimore** [comment]
I meant [MultiDiscrete](https://gymnasium.farama.org/api/spaces/fundamental/#gymnasium.spaces.MultiDiscrete), where each observation has discrete values [0,1], so as to be compatible with a bigger set of learning algorithms...?

**Comment by vamsianumula** [comment]
Yeah, MultiDiscrete can also be used, but even that too seems to supports A2C and PPO variants [here](https://stable-baselines3.readthedocs.io/en/master/guide/algos.html)

Shall we try to achieve the same using Box space with range [0,1]. If dtype can be specified to an integer for box space, this can be a workaround.  Else, can we try with rounding off the values in range (0,1)?

**Comment by smarianimore** [comment]
Yes you're right my bad.

I would proceed with a first implementation with MultiDiscrete, which is a good compromise (imho) between future extendability and current adherence to the actual observations of the model

Then after testing we can imagine to extend it to a Box space

what do you think?

**Comment by vamsianumula** [comment]
yeah, lets do it that way. I will proceed with MultiDiscrete.

**Comment by vamsianumula** [comment]
Hi @smarianimore, I have made changes to env and now its compatible with stable baselines3. Can you review this PR: [https://github.com/LucaInis/Slime-Enviroment-GIT-/pull/5](https://github.com/LucaInis/Slime-Enviroment-GIT-/pull/5) ? I have included an output of test run in it.

**Comment by smarianimore** [comment]
Sure @vamsianumula , doing it ASAP (was sick and then out for work)

**Comment by smarianimore** [comment]
closed by merged pull request #6 with commit #6ffea52e7082f3e9d84c5108843657e4324cdaec
